# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'module.exports = jo32'
tagline:          'a blog about jo32'
description:      'a blog about jo32'
url:              http://jiangdl.com
baseurl:          '/'
paginate:         5

author:
  name:           'jo32'
  url:            https://github.com/jo32

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/jo32/jo32.github.io
